trigger:
- '*'

jobs:
  - job: WindowsBuild
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: | 
        choco install python3 -y
        py.exe -m pip install cmake
        py.exe -m pip install conan
      displayName: Install CMake, Conan
      # for now it does its job ... i know the  hardcoded paths are ugly... 
    - script: |
        set PATH=%PATH%;C:\hostedtoolcache\windows\Python\3.12.7\x64\Scripts
        conan --version  # Now you can use Conan
        conan profile detect
        powershell -Command "(gc C:\Users\VssAdministrator\.conan2\profiles\default) -replace 'compiler.cppstd=14', 'compiler.cppstd=20' | Out-File -encoding ASCII C:\Users\VssAdministrator\.conan2\profiles\default"
        powershell -Command "(gc C:\Users\VssAdministrator\.conan2\profiles\default) -replace 'compiler.runtime=dynamic', 'compiler.runtime=static' | Out-File -encoding ASCII C:\Users\VssAdministrator\.conan2\profiles\default"
      displayName: 'Init Conan'
    - script: |
        set PATH=%PATH%;C:\hostedtoolcache\windows\Python\3.12.7\x64\Scripts
        conan install . -of build --build missing
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=".\build\conan_toolchain.cmake"
        cmake --build ./build --config Release -j6
      displayName: 'Win Release Build'
    - script: |
        .\build\bin\Release\unittests.exe
      displayName: 'Run Unittests'
    - script: |
        .\build\bin\Release\example.exe examples
      displayName: 'Run example'
