trigger:
- '*'


jobs:
  - job: WindowsBuild
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: | 
        choco install -y python3
        py.exe -m pip install cmake
        py.exe -m pip install conan
      displayName: Install CMake, Conan
    # - script: echo '##vso[task.prependpath]C:\hostedtoolcache\windows\Python\3.12.0\x64\Scripts'  # Replace with the actual path to Conan installation
    #   displayName: Extend PATH
    # C:\hostedtoolcache\windows\Python\3.12.0\x64\Scripts\conan.exe --version
    - script: |
        set PATH=%PATH%;C:\hostedtoolcache\windows\Python\3.12.0\x64\Scripts
        conan.exe --version  # Now you can use Conan
        conan.exe profile detect
        powershell -Command "(gc C:\Users\VssAdministrator\.conan2\profiles\default) -replace 'compiler.cppstd=14', 'compiler.cppstd=17' | Out-File -encoding ASCII C:\Users\VssAdministrator\.conan2\profiles\default"
        powershell -Command "(gc C:\Users\VssAdministrator\.conan2\profiles\default) -replace 'compiler.runtime=dynamic', 'compiler.runtime=static' | Out-File -encoding ASCII C:\Users\VssAdministrator\.conan2\profiles\default"
      displayName: 'Init Conan'
    - script: |
        set PATH=%PATH%;C:\hostedtoolcache\windows\Python\3.12.0\x64\Scripts
        conan install . -of build --build missing
        cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=".\build\conan_toolchain.cmake"
        cmake --build ./build --config Release -j6
        .\build\bin\Release\unittests.exe
        .\build\bin\Release\box.exe .\examples\features\
      displayName: 'Win Release Build'
