trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- script: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
  displayName: 'Install CMake'

- script: cmake --version
  displayName: 'Verify CMake installation'

- script: |
    cmake -S . -B ./build
    cmake --build ./build
  displayName: 'CMake Build'
