trigger:
- '*'


jobs:
  - job: WindowsBuild
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: | 
        choco install -y python3
        py.exe -m pip install cmake
        py.exe -m pip install conan
      displayName: Install tools 
    - script: py.exe -m pip show conan  # Now you can use Conan
      displayName: 'Verify Conan installation'
    - script: cmake --version  # Now you can use Conan
      displayName: 'Verify CMake installation'
    # - script: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
    #   displayName: 'Install CMake'
    # - script: python3.exe --version
    #   displayName: check python3
    # - script: python.exe --version
    #   displayName: check python
    # - script: py.exe --version
    #   displayName: check pz
    - script: |
        cmake -S . -B ./build
        cmake --build ./build -j6
      displayName: 'CMake Build'
