name: CI

on:
  push:
    branches: [ "**" ]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    container:
      image: those90/dev-image:1.0
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          conan install . -of ./build_gcc --build missing 
          cmake -S . -B ./build_gcc -DCMAKE_TOOLCHAIN_FILE=./build_gcc/conan_toolchain.cmake
          cmake --build ./build_gcc -j12
      - name: unittests
        run: ./build_gcc/bin/unittests

  # build-clang:
  #   container: those90/dev-image:1.0
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: build
  #       run: |
  #         conan install . -of ./build_clang --build missing -pr clang
  #         cmake -S . -B ./build_clang -DCMAKE_TOOLCHAIN_FILE=./build_clang/conan_toolchain.cmake -DCMAKE_CXX_COMPILER=clang++-17 -DCMAKE_C_COMPILER=clang-17
  #         cmake --build ./build_clang -j12      
  #     - name: unittests
  #       run: ./build_clang/bin/unittests
